services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      AUCTION_DURATION: ${AUCTION_DURATION:-20s}
      BATCH_INSERT_INTERVAL: ${BATCH_INSERT_INTERVAL:-20s}
      MAX_BATCH_SIZE: ${MAX_BATCH_SIZE:-4}
      MONGODB_URL: mongodb://admin:admin@mongodb:27017/auctions?authSource=admin
      MONGODB_DB: auctions
    command: sh -c "/auction"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - localNetwork

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge
